# Generated by Django 5.2.3 on 2025-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='faturamento',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Faturado sem taxa', 'Faturado sem taxa'), ('Faturado com taxa', 'Faturado com taxa'), ('Pendente sem Contrato', 'Pendente sem Contrato'), ('Pendente Sem Termo', 'Pendente Sem Termo'), ('Sem Custo', 'Sem Custo'), ('Dados invalidos', 'Dados invalidos'), ('Reprovado Pelo CEO', 'Reprovado Pelo CEO')], default='Pendente', max_length=1200),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Tipo de Faturamento', 'Tipo de Faturamento'), ('Aquisicão Nova', 'Aquisicão Nova'), ('Manutenção', 'Manutenção'), ('Aditivo', 'Aditivo'), ('Acessórios', 'Acessórios'), ('Extravio', 'Extravio'), ('Teste', 'Teste'), ('Spot', 'Spot'), ('Isca Fast', 'Isca Fast'), ('Isca Fast - Agente', 'Isca Fast - Agente'), ('Antenista', 'Antenista'), ('Reversa', 'Reversa'), ('Isca FAST', 'Isca FAST'), ('Estoque Antenista', 'Estoque Antenista'), ('Renovação', 'Renovação')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='status_faturamento',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Faturado sem taxa', 'Faturado sem taxa'), ('Faturado com taxa', 'Faturado com taxa'), ('Pendente sem Contrato', 'Pendente sem Contrato'), ('Pendente Sem Termo', 'Pendente Sem Termo'), ('Sem Custo', 'Sem Custo'), ('Dados invalidos', 'Dados invalidos'), ('Reprovado Pelo CEO', 'Reprovado Pelo CEO')], default='Pendente', max_length=50, null=True),
        ),
    ]
