# Generated by Django 5.2.3 on 2025-09-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('fabricante', models.CharField(max_length=200, verbose_name='Fabricante')),
                ('telefone_fabricante', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email_fabricante', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cadastro de Tipo de Produto',
                'verbose_name_plural': 'Cadastros de Tipos de Produtos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='EntradaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('id_equipamento', models.CharField(max_length=100, verbose_name='ID (Número do Equipamento)')),
                ('data', models.DateTimeField(verbose_name='Data (datetime)')),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Nota (Valor de Compra)')),
                ('numero_nota_fiscal', models.CharField(max_length=50, verbose_name='Número de Nota Fiscal')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('codigo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.cadastrotipoproduto', verbose_name='Código do Produto (FK)')),
            ],
            options={
                'verbose_name': 'Entrada de Produto',
                'verbose_name_plural': 'Entradas de Produtos',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
