# Generated by Django 5.2.3 on 2025-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_cadastrotipoproduto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproduto',
            name='ids_equipamentos',
            field=models.TextField(blank=True, null=True, verbose_name='IDs dos Equipamentos (separados por vírgula)'),
        ),
    ]
