# Generated by Django 5.2.3 on 2025-09-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_entradaproduto_ids_equipamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproduto',
            name='ids_equipamentos_timestamps',
            field=models.TextField(blank=True, null=True, verbose_name='Timestamps dos IDs (JSON)'),
        ),
    ]
