# Generated by Django 5.2.3 on 2025-09-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0005_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrodemanutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(blank=True, choices=[('Manutenção', 'Manutenção'), ('Devolução/Estoque', 'Devolução/Estoque')], max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, choices=[('', ''), ('Manutenção', 'Manutenção'), ('Devolução/Estoque', 'Devolução/Estoque')], max_length=50, null=True)),
                ('tipo_customizacao', models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + Imã', 'Termo branco + Imã'), ('Termo branco + D.F', 'Termo branco + D.F'), ('Termo branco slim', 'Termo branco slim'), ('Termo branco slim + D.F +EQT', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT', 'Termo cinza slim + D.F +EQT'), ('Termo branco (isopor)', 'Termo branco (isopor)'), ('Termo branco - bateria externa', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo brabco |marrim-slim', 'Termo brabco |marrim-slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], max_length=50, null=True)),
                ('recebimento', models.CharField(blank=True, choices=[('Correios/Transportadora', 'Correios/Transportadora'), ('Entrega na base', 'Entrega na base'), ('Motoboy', 'Motoboy')], max_length=50, null=True)),
                ('entregue_por_retirado_por', models.CharField(blank=True, choices=[('Correios/Transportadora', 'Correios/Transportadora'), ('Entrega na base', 'Entrega na base'), ('Motoboy', 'Motoboy')], default='', max_length=50, null=True)),
                ('id_equipamentos', models.TextField(blank=True, default='', max_length=1200)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('Descartavel', 'Descartavel'), ('Retornavel', 'Retornavel')], max_length=50, null=True)),
                ('customizacaoo', models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + Imã', 'Termo branco + Imã'), ('Termo branco + D.F', 'Termo branco + D.F'), ('Termo branco slim', 'Termo branco slim'), ('Termo branco slim + D.F +EQT', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT', 'Termo cinza slim + D.F +EQT'), ('Termo branco (isopor)', 'Termo branco (isopor)'), ('Termo branco - bateria externa', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo brabco |marrim-slim', 'Termo brabco |marrim-slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], default='', max_length=250)),
                ('numero_equipamento', models.TextField(blank=True, default='', max_length=2500)),
                ('observacoes', models.TextField(blank=True, default='', max_length=250)),
                ('tratativa', models.CharField(blank=True, choices=[('Oxidação', 'Oxidação'), ('Placa Danificada', 'Placa Danificada'), ('USB Danificado', 'USB Danificado'), ('Botão de acionamento Danificado', 'Botão de acionamento Danificado'), ('Antena LoRa Danificada', 'Antena LoRa Danificada'), ('USB Sem problemas Identificados', 'USB Sem problemas Identificados'), ('Antena 4G danificada', 'Antena 4G danificada'), ('Avarias Fisicas Graves', 'Avarias Fisicas Graves')], max_length=50, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('status', models.CharField(blank=True, default='Pendente', max_length=50, null=True)),
                ('status_tratativa', models.CharField(blank=True, choices=[('Pendente de Tratativa', 'Pendente de Tratativa'), ('Tratada', 'Tratada'), ('Faturada', 'Faturada')], default='Pendente de Tratativa', max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_nome', to='clientes.clientes')),
                ('tipo_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_produto', to='produtos.cadastrotipoproduto')),
            ],
            options={
                'verbose_name': 'Registro de Manutenção',
                'verbose_name_plural': 'Registros de Manutenção',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(blank=True, choices=[('Oxidação', 'Oxidação'), ('Placa Danificada', 'Placa Danificada'), ('Placa danificada SEM CUSTO', 'Placa danificada SEM CUSTO'), ('USB Danificado', 'USB Danificado'), ('USB Danificado SEM CUSTO', 'USB Danificado SEM CUSTO'), ('Botão de acionamento Danificado', 'Botão de acionamento Danificado'), ('Botão de acionamento Danificado SEM CUSTO', 'Botão de acionamento Danificado SEM CUSTO'), ('Antena LoRa Danificada', 'Antena LoRa Danificada'), ('Sem problemas Identificados', 'Sem problemas Identificados'), ('Antena 4G danificada', 'Antena 4G danificada'), ('Avarias Fisicas Graves', 'Avarias Fisicas Graves')], max_length=50, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_registros/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='imagens_registros/')),
                ('id_equipamento', models.CharField(blank=True, max_length=255)),
                ('faturamento', models.CharField(blank=True, choices=[('', ''), ('Com_Custo', 'Com Custo'), ('Sem_Custo', 'Sem Custo')], default='', max_length=50, null=True)),
                ('observacao2', models.CharField(blank=True, default='', max_length=50)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='registro_manutencao.registrodemanutencao')),
            ],
            options={
                'verbose_name': 'Imagem de Registro',
                'verbose_name_plural': 'Imagens de Registros',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='retorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('Oxidação', 'Oxidação'), ('Placa Danificada', 'Placa Danificada'), ('Placa danificada SEM CUSTO', 'Placa danificada SEM CUSTO'), ('USB Danificado', 'USB Danificado'), ('USB Danificado SEM CUSTO', 'USB Danificado SEM CUSTO'), ('Botão de acionamento Danificado', 'Botão de acionamento Danificado'), ('Botão de acionamento Danificado SEM CUSTO', 'Botão de acionamento Danificado SEM CUSTO'), ('Antena LoRa Danificada', 'Antena LoRa Danificada'), ('Sem problemas Identificados', 'Sem problemas Identificados')], max_length=100)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('id_equipamentos', models.TextField(blank=True, default='', max_length=1000)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.clientes')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.cadastrotipoproduto')),
            ],
            options={
                'verbose_name': 'Retorno',
                'verbose_name_plural': 'Retornos',
                'ordering': ['-id'],
            },
        ),
    ]
