# Generated by Django 5.2.3 on 2025-09-15 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(blank=True, choices=[('Diretoria', 'Diretoria'), ('Inteligência', 'Inteligência'), ('Faturamento', 'Faturamento'), ('Expedição', 'Expedição'), ('Configuração', 'Configuração'), ('Quality', 'Quality'), ('Área Técnica', 'Área Técnica'), ('Comercial', 'Comercial')], max_length=255, null=True, verbose_name='Setor')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Ticket')),
                ('descricao_erro', models.TextField(verbose_name='Descrição do Problema')),
                ('correcao', models.TextField(blank=True, null=True, verbose_name='Correção Aplicada')),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Média', max_length=20, verbose_name='Prioridade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Resolvido', 'Resolvido'), ('Fechado', 'Fechado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=255, verbose_name='Status')),
                ('devolutiva', models.TextField(blank=True, null=True, verbose_name='Devolutiva')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
